### — Imports

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import pandas as pd
import plotly.express as px
from pathlib import Path
from dotenv import load_dotenv

sys.path.append(str(Path().resolve().parent))
from src.scraper import scrape_all_cities

load_dotenv(dotenv_path=Path().resolve().parent / ".env")
print("Imports OK")

Imports OK

### — Chargement des villes (output notebook 01)

In [3]:
df_cities = pd.read_csv(Path().resolve().parent / "data" / "raw" / "cities.csv")
print(f"{len(df_cities)} villes chargées")
df_cities[["city_id", "city", "weather_score", "rank"]].head()

35 villes chargées

   city_id         city  weather_score  rank
0       28    Collioure          16.10     1
1       29  Carcassonne          11.72     2
2        9   Strasbourg           8.64     3
3        8        Lille           6.53     4
4       11       Colmar           6.37     5

### — Paramètres

In [4]:
CHECKIN             = "2025-06-01"
CHECKOUT            = "2025-06-03"
MAX_HOTELS_PER_CITY = 20

### — Test sur 2 villes

df_test = scrape_all_cities(
    df_cities.head(2),
    max_hotels_per_city=3,
    headless=False,        # Chrome visible pour vérifier
    force_refresh=True     # ignore le cache pour le test
)
df_test

###  — Scraping complet

In [5]:
df_hotels = scrape_all_cities(
    df_cities,
    #checkin=CHECKIN,
    #checkout=CHECKOUT,
    max_hotels_per_city=MAX_HOTELS_PER_CITY,
    #delay_range=(2, 4)
    headless=False,        
    force_refresh=True 
)

print(f"\nTotal : {len(df_hotels)} hôtels")
print(f"Valeurs manquantes :\n{df_hotels.isnull().sum()}")
df_hotels.head()

Scraping : Collioure... OK (20 hôtels)
Scraping : Carcassonne... OK (20 hôtels)
Scraping : Strasbourg... OK (20 hôtels)
Scraping : Lille... OK (20 hôtels)
Scraping : Colmar... OK (20 hôtels)
Scraping : Eguisheim... OK (20 hôtels)
Scraping : Chateau du Haut Koenigsbourg... OK (20 hôtels)
Scraping : Saintes Maries de la mer... OK (20 hôtels)
Scraping : Toulouse... OK (20 hôtels)
Scraping : Besancon... OK (20 hôtels)
Scraping : Avignon... OK (20 hôtels)
Scraping : Uzes... OK (20 hôtels)
Scraping : Bormes les Mimosas... OK (20 hôtels)
Scraping : Aix en Provence... OK (20 hôtels)
Scraping : Marseille... OK (20 hôtels)
Scraping : Le Havre... OK (20 hôtels)
Scraping : Nimes... OK (20 hôtels)
Scraping : Amiens... OK (20 hôtels)
Scraping : Bayeux... OK (20 hôtels)
Scraping : Mont Saint Michel... OK (20 hôtels)
Scraping : Aigues Mortes... OK (20 hôtels)
Scraping : Cassis... OK (20 hôtels)
Scraping : St Malo... OK (20 hôtels)
Scraping : Gorges du Verdon... OK (20 hôtels)
Scraping : Dijon... OK (20 hôtels)
Scraping : Rouen... OK (20 hôtels)
Scraping : Grenoble... OK (20 hôtels)
Scraping : Montauban... OK (20 hôtels)
Scraping : Annecy... OK (20 hôtels)
Scraping : Lyon... OK (20 hôtels)
Scraping : Ariege... OK (20 hôtels)
Scraping : Paris... OK (20 hôtels)
Scraping : Bayonne... OK (20 hôtels)
Scraping : Biarritz... OK (20 hôtels)
Scraping : La Rochelle... OK (20 hôtels)

Terminé ! 700 hôtels sauvegardés dans data/raw/hotels_cache.csv

Total : 700 hôtels
Valeurs manquantes :
city_id        0
city           0
hotel_name     0
score          6
distance      40
price_eur      1
dtype: int64

,city_id,city,hotel_name,score,distance,price_eur
0,28,Collioure,La Frégate,8.3,200 m du centre,331.0
1,28,Collioure,Hotel Méditerranée,7.9,350 m du centre,NaN
2,28,Collioure,,NaN,"0,7 km du centre",772.0
3,28,Collioure,Hôtel & Spa Le Madeloc - Collioure Centre,0.6,"0,6 km du centre",472.0
4,28,Collioure,Appartement de charme Padiolka Avg,0.8,"0,8 km du centre",384.0

### — Sauvegarde

In [6]:
out = Path().resolve().parent / "data" / "raw" / "hotels.csv"
df_hotels.to_csv(out, index=False, encoding="utf-8-sig")
print(f"Sauvegardé : {out}")

Sauvegardé : /home/ibraba/tourisme-france/data/raw/hotels.csv

### — Nettoyage rapide avant sauvegarde finale

In [ ]:
# suppression ligne dont nom manquant

df_hotels = df_hotels.dropna(subset=["hotel_name"]).reset_index(drop=True)
print(f"Après nettoyage : {df_hotels.shape}")
df_hotels.isnull().sum()

Après nettoyage : (700, 6)

city_id        0
city           0
hotel_name     0
score          6
distance      40
price_eur      1
dtype: int64

### Sauvegarde finale de la version nettoyée :

In [17]:
out = Path().resolve().parent / "data" / "raw" / "hotels.csv"
df_hotels.to_csv(out, index=False, encoding="utf-8-sig")
print(f"Sauvegardé : {out}")

Sauvegardé : /home/ibraba/tourisme-france/data/raw/hotels.csv